### PR TITLE
Problem: we are not testing rust

### PR DESCRIPTION
**Pull request by clacke**
The Mozilla Rust overlay is impure.

Solution: Make the manifest download fixed-output.

Add rust tests to release.nix and .travis.yml.

The Linux test in .travis.yml is a bit ugly, but will go away once
travisOrder is done over on racket2nix and can be brought over.

### CODE REVIEW

**Comment by clacke** [comment]
slow merge

**Comment by sjmackenzie** [comment]
Do you know what happened to travis? (I restarted a build to test that macos nix issue https://travis-ci.org/fractalide/fractalide/jobs/385683241 I wonder if I created a weird machine :-) )

**Comment by clacke** [comment]
Yeah I don't know I just figured the queue is busy and we need to wait a bit.

**Comment by clacke** [comment]
clacke / racket2nix-clacke  isn't starting any new jobs either. Global travis issue, I guess.

**Comment by sjmackenzie** [comment]
Okay, won't bother with the noop, shall I merge anyway? We can see the results on hydra.

**Comment by sjmackenzie** [comment]
Ah ha! Travis couldn't parse the .travis.yml https://travis-ci.org/fractalide/fractalide/requests

**Pull request merged**
