### PR TITLE
Problem: hard reproducible bug introduced in nixpkgs caused generate-…

### PR DESCRIPTION
**Pull request by sjmackenzie**
…msg to fail

Solution: the simplest solution is to change the package details of
generate-msg so that it conforms with cargo regulations. i.e. use an
underscore in the package name.

Now Travis-ci, macos, ubuntu and nixos should all see the same build
product -> generate_msg and not generate-msg on some machines.

### CODE REVIEW

**Comment by clacke** [comment]
Pinpointing now what changed. I reverted your previous fix and I reliably fail on recent nixpkgs-unstable and succeed on March nixpkgs-unstable.

Let's see the result when I'm back home tonight (the below is with a patched `fractalide` where `pkgs/default.nix` gets its `pkgs` from my bisecting `nixpkgs-channels`):

```
$ git bisect start; git bisect good 38d6699a936f8bf60c90c2fc11f5e584313b7740; git bisect bad origin/nixpkgs-unstable; git bisect run nix-build ../../fractalide/fractalide/tests/ 
Previous HEAD position was 8a104014526... hackage-packages.nix: automatic Haskell package set update
HEAD is now at 38d6699a936... Merge #37731: procps-ng: update project location
Bisecting: 1778 revisions left to test after this (roughly 11 steps)

```

**Comment by clacke** [comment]
Yes, I just cannot handle not knowing why specifically it failed at this point. ;-)

**Comment by clacke** [comment]
```
-        if [ "$crate_name_" -ne "$crate_name" ]; then
+        if [ "$crate_name_" != "$crate_name" ]; then
           mv target/bin/$crate_name_ target/bin/$crate_name
         fi
```

Right! That was probably that super annoying `generate_msg: expected integer` (or something) message we saw! (on a line number that didn't exist but anyway)

So this was a real bug fix, and we happened to have adapted to the bug. That's fair.

But let's go and pin nixpkgs, so that no bug fixes ever bite us again unawares.

**Comment by clacke** [comment]
I read that code line several times and was screaming in my mind "it's there why isn't it doing it" and never realized there was a version with `-ne` and a version with `!=`. I'm supposed to know the difference, but then so is the actual genius who wrote this code, so I can forgive myself. ;-)

**Comment by clacke** [comment]
The fix was in NixOS/nixpkgs#37928 .

**Comment by sjmackenzie** [comment]
oh neat you found it :-) Yes pinning is probably the best way forward for the mean time. But pinning means you do a costly check to see if the pin is downloaded which can add a good few 10s of seconds every time you build. So we should probably be careful about this.

**Comment by clacke** [comment]
Each time ... Right, on Travis. 10s of seconds sounds like an exaggeration. Either way, that's still pretty cheap compared to the other things it does.

**Comment by sjmackenzie** [comment]
Travis is one thing, but when Hyperflow start calling nix to build the node hierarchies that's when you'll feel it.

**Comment by sjmackenzie** [comment]
It's quite hard to maintain a fast development/build/test cycle when you need to go through nix, hence the desperate need for incremental compilation and limiting compilation units to libraries and agents. I'm also concerned about having graphs described in racket code instead of being a text file that's quickly written to disk. Anyway, this point is yet to be determined in the racket implementation. I once pinned nixpkgs but changed back as of the expense of the pin check became too much. It's much faster when you just use your local nixpkgs.  My hope is that we can achieve DrRacket levels of development/build/test cycles. A lofty goal indeed.

**Comment by sjmackenzie** [comment]
It'd be nice if we could have a development mode that doesn't go through nix (i.e. hyperflow doesn't call nix) but this would be impossible due to the need for fractal inclusion.

**Comment by sjmackenzie** [comment]
It can go up to 10s of seconds depending on your connection, maybe nix 2.0 does something faster?

**Comment by clacke** [comment]
When you run locally, it will fetch the pinned nixpkgs exactly once ever.

**Comment by sjmackenzie** [comment]
Sure it'll dl once, but it has to check from the source, that's why I said "pin check". Anyway, it's pinned now lets see if it was the develop/build/run cycle is affected!

**Pull request merged**
