### PR TITLE
 Problem: Not running `raco test` on Travis

### PR DESCRIPTION
**Pull request by clacke**
Solution: Create rkt-tests, add to release.nix.

### CODE REVIEW

**Comment by clacke** [comment]
We had a question in some context the other as to whether Travis would pull zips from hydra or not.

> copying path '/nix/store/zfl5grxh817nlci4ffa3f1gf4hm3y7l2-net-cookies-doc.zip' from 'https://hydra.fractalide.com'...

That answers that.

**Comment by clacke** [comment]
The reason Travis is now rebuilding most of our dependencies is because I bumped racket2nix, and racket2nix itself doesn't depend on those packages, so this is the first time the new racket2nix builds them except locally on my machine.

**Comment by clacke** [comment]
More evidence for fractalide/racket2nix#153 : 

```
building '/nix/store/jc7cgza2bsqgmsz1pbw5fi1w0wgkzsfr-gui-lib.drv'...
unpacking sources
unpacking source archive /nix/store/zmmnnf9i0s58l2rq5nx9m8z010ddncfx-r6rs-doc.zip
/private/tmp/nix-build-r6rs-doc.drv-0
patching sources
installing
WARNING: This derivation should not have been depended on.
Any derivation depending on this one should have depended on one of these instead:
racket-doc compatibility compatibility-doc data-doc math-doc plot-doc db-doc web-server-doc scribble-doc typed-racket-doc
```

Oddly enough this happens on Darwin but not on Linux (in this very specific case).

Can't wait for the glorious future when I have time to rip out my whole rickety package relation resolver and replace it with a gleaming datalog ruleset.

**Comment by clacke** [comment]
Oh! Travis too, eh.

The problem is that `graph` pulls in `racket-doc`, which has 42 circular deps with 90 transitive deps.

I'll fix stchang/graph#35 in September, shouldn't be too hard.

**Comment by clacke** [comment]
Wow, hydra is pretty bad at explaining (it doesn't) that builds failed due to disk space.

**Comment by sjmackenzie** [comment]
Yeah I restarted a bunch of failed stuff, seems to be chugging along nicely. Let's see.

**Comment by sjmackenzie** [comment]
Yeah, dying again https://hydra.fractalide.com/build/276 `<3>out of memory`

**Comment by clacke** [comment]
I had to kill the pict-lib build to make it terminate. Now it re-ran nicely.

**Pull request merged**
