### PR TITLE
Problem: rust-cardano backend not integrated

### PR DESCRIPTION
**Pull request by sjmackenzie**
Solution: use a hacky git submodule approach till upstream
decides on a crates.io publication strategy.

(i.e. separated individual crates or a monolithic crate; preferably
the former)

Till then this commit brings the code into scope so we can start
building on it.

### CODE REVIEW

**Comment by clacke** [comment]
Why a submodule instead of a derivation? Is carnix making that difficult?

**Comment by sjmackenzie** [comment]
Carnix creates transdeps from a Cargo.toml file, 2nd we cannot put a git url in the cargo.toml as carnix barfs it. Better to wait for upstream to publish to crates.io. But this introduces an issue with hydra, which doesn't like git submodules. (my patch won't apply in the `patchPhase` of hydra's build)

**Comment by clacke** [comment]
Hmm yes. In the racket2nix case I solve this by just feeding racket2nix a store path, but then the hydra sandbox gets upset at that instead, so I need to detect for that and make store paths into fixed-output derivations.

So to go around this, carnix would need to incorporate the same form of workaround.

**Comment by clacke** [comment]
Otherwise we could do it like I originally did it in racket2nix's bootstrap before it handled nix paths well enough: Generate the toml (in this case) with the nix path (or whatever dummy path really), then override the generated nix to point at a derivation instead.

**Comment by sjmackenzie** [comment]
I think the simplest solution is hack hydra to support git submodules (iohk made a similar patch) then once those cardano crates are published remove the submodule

**Pull request merged**
