### PR TITLE
Problem: travis doesn't want to build racket on darwin

### PR DESCRIPTION
**Pull request by clacke**
Solution: Add darwin to racket.meta.platforms.

### CODE REVIEW

**Comment by clacke** [comment]
Too fast! Anyway, this will probably work. Let's see how it looks on master.

**Comment by clacke** [comment]
I realized I wouldn't have had to rebase that. I could have just canceled and restarted the job on Travis -- it clones a fresh one from pull/<number>/merge every time.

**Comment by sjmackenzie** [comment]
Ah okay, actually all you need to do is `git push origin <branch> -f` and travis will automatically restart. I'll let you hack on this one without merging too quickly :-)

**Comment by clacke** [comment]
> error: Package ‘racket-6.12’ in /nix/store/vmjf3fqrwf30a2317fl5jrl222p0i2gh-nixpkgs-18.09pre133932.ee28e35ba37/nixpkgs/pkgs/development/interpreters/racket/default.nix:82 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.


urg. So apparently on Travis there's an `-apple-` in there.

**Comment by clacke** [comment]
> all you need to do is git push origin <branch> -f

What I meant was, I wouldn't even have had to do that. Or, "even" depends on which one you would think is less of a bother. But if I had just restarted the mac build directly on Travis I wouldn't have triggered two new linux builds.

**Pull request merged**
