### PR TITLE
Problem: not making use of hydra to cut test times

### PR DESCRIPTION
**Pull request by clacke**
Solution: Add our hydra's address and key to nix.conf

### CODE REVIEW

**Comment by clacke** [comment]
Works in theory, doesn't break anything, properly discovers there are packages on hydra, but they're not signed.

I *think* as soon as I do something with racket2nix and propagate that, things should shake loose and we'll save a whole bunch of time on tests.

Except on darwin.

**Comment by clacke** [comment]
Oh screw it I'm turning of signature checking. I want to see this miracle tonight before I go to bed.

**Comment by clacke** [comment]
It's happily downloading things. Nice.

> these paths will be fetched (0.12 MiB download, 128.31 MiB unpacked):

Wow yikes. Ok.

**Comment by clacke** [comment]
I am happy to report that:

    $ ./support/utils/nix-build-travis-fold.sh --fallback -I fractalide=. -A fractalide release.nix

... now finishes in 122.85 s.

**Comment by clacke** [comment]
Fails on darwin because NIX_PATH something.

**Comment by clacke** [comment]
Ok, now Darwin is also ready for some far away future when we have set up a darwin slave.

This is ready to merge.

**Comment by clacke** [comment]
Travis on master took 3 mins for Linux machines and 15 mins for Darwin.

**Comment by sjmackenzie** [comment]
Hmm I think I should get a second hand mac-mini then run it as a build slave from home.

**Comment by clacke** [comment]
Good idea. That would work.

**Pull request merged**
