### PR TITLE
Problem: rust is not reproducible

### LINKED ISSUE #88: Problem: using rust nightly means an update everyday - utterly laborious
Solution: nightly is used because fractalide uses a `custom allocator` which isn't present in rust `beta`. Hence implement the custom allocator in `beta`

### LINKED ISSUE #132: Problem: rust is failing to build

### PR DESCRIPTION
**Pull request by clacke**
We are updating from nightly every day.

Solution: Pin rust to 2018-04-01.

Closes #88
Closes #132

### CODE REVIEW

**Comment by clacke** [comment]
Testing this locally, but it takes a long time. _Please don't merge until everything is green_.

**Comment by clacke** [comment]
Nope nope.

    /nix/store/3y0wxpkxzs6yz73iw35d17qr1wp4p2i4-stdenv-linux/setup: line 1222: /nix/store/mmbcf4x5p4xm42b42638clvvwjwi32nw-rust_generate-msg-0.1.0/bin/generate_msg: No such file or directory

Does this pin only rust, and we need to pin the cargo repo as well?

**Comment by sjmackenzie** [comment]
Cargo should be pinned too.

**Comment by sjmackenzie** [comment]
I'm going to merge this anyway, it seems a valid PR just needs a bit of tweaking to find the right version that builds. Are you still on this or do you want to amend it?

**Pull request merged**
