### PR TITLE
Problem: default.nix was too complicated

### PR DESCRIPTION
**Pull request by ericsagnes**
**WIP: Do not merge yet!**

Solution: simplify it.

This change slightly how `default.nix` is working and require an update in the documentation and need a review to be sure the changes are not removing any functionality.

Before this PR:

```sh
$ nix-build --argstr rs test_nand
```

---

After this PR:

```sh
$ nix-build --argstr node test_nand
```
The backend default is rust, to change it to something else, eg purs:

```
$ nix-build --argstr node test_nand  --argstr backend purs
```

cc @sjmackenzie

### CODE REVIEW

**Comment by sjmackenzie** [comment]
I see, yes this is better!

**Comment by ericsagnes** [comment]
Updated the docs so this should be ready to merge now.
By the way, by testing the example from the doc I noticed that the `worktest_bench` test was failing with the following error:

```
About to use rustc to compile some lib - rustc-serialize
warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type

warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type

error[E0460]: found possibly newer version of crate `memchr` which `aho_corasick` depends on
   --> src/lib.rs:475:1
    |
475 | extern crate aho_corasick;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: perhaps that crate needs to be recompiled?
    = note: crate `memchr` path #1: /nix/store/2ncxxpr82a3hllsvaw5vp8vwf5v9vdj0-memchr/libmemchr.rlib
    = note: crate `aho_corasick` path #1: /nix/store/7ya728q7pn4azs8l8kam914xpsl0vp2d-aho-corasick/libaho_corasick.rlib

error: aborting due to previous error

builder for ‘/nix/store/ydlgak4jnbx26lwi01ad8vvkz3y38jaw-regex.drv’ failed with exit code 101
cannot build derivation ‘/nix/store/bzsqb7vi5aijk53gsr3indhdqnbzvhm2-rs_http.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6pvf0hldc3a7k1nwjbjw57bbyhj2c32l-rs_workbench.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/lv4f577347grknvx3zrbs5w1n7wkql83-rs_test.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/qqlkjbl4vsbw9clwfdbw8vb0lh12sh7n-rs_test.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/qqlkjbl4vsbw9clwfdbw8vb0lh12sh7n-rs_test.drv’ failed
```

The same error happens on master so this should not be due to this PR contents.

It might be worth to set a travis file to run a test suite on every commit.

**Comment by sjmackenzie** [comment]
This error is due to nixcrates it's not related to this issue.

**Comment by sjmackenzie** [comment]
I'll be looking at this to replace nixcrates https://nest.pijul.com/pmeunier/nix-rust but this is after all this non-code related stuff has passed!

**Comment by ericsagnes** [comment]
Added a commit to provide a way to run some nix tests + a travis file.

Running `nix-build tests` will run the tests defined in `test/default.nix` (building `test_nand`, `bench` and `bench_load`), and if travis is set up on this repo, it will run that command upon every commit.

**Comment by sjmackenzie** [comment]
okay just activated it!

**Comment by sjmackenzie** [comment]
maybe good to add the `--keep-going` argument to build all the components?

**Comment by ericsagnes** [comment]
I think that in the context of CI it makes more sense to fail fast as we only want to know if tests are passing or not.

`--keep-going` would force travis to build more even if a test is failing.
And as travis do not cache build products like Hydra does, it would just consume more computing power for no real added value.

**Comment by sjmackenzie** [comment]
okay fair enough

**Comment by sjmackenzie** [comment]
"should be ready to merge now" <-- ah sorry didn't read that.

**Comment by sjmackenzie** [comment]
thanks! It feels much cleaner :+1:

**Pull request merged**
