### PR TITLE
Documentation: Switching to asciidoctor

### PR DESCRIPTION
**Pull request by ericsagnes**
Switch documentation related files from markdown to asciidoc.

### Motivation

Asciidoc is more flexible and allow to include sections of files like done [here](https://raw.githubusercontent.com/ericsagnes/fractalide/feat/doc-adoc/doc/index.adoc) (`tags=doc` parts). That allow to reuse files between the repository and the documentation avoiding redundant information.

Also, asciidoc is almost a superset of markdown so the overhead of this switch is quite low.

GitHub process asciidoc without trouble, [example](https://github.com/ericsagnes/fractalide/tree/feat/doc-adoc).

### Preview

The documentation using asciidoc can be built with by running `nix-build doc` from repository root.
The documentation will be generated in HTML format in `result/share/doc/fractalide/index.html`.

### TODO before merging

This PR is in a preview state, and the following points should be addressed before merging:

- [x] Put the documentation section in the right order.
- [x] Fix broken links to the repo in HOWTO and similar pages.
- [x] Fix titles levels 

cc @sjmackenzie

### CODE REVIEW

**Comment by ericsagnes** [comment]
### Links

Fixed all the links I could figure.

I will need some help with the following broken links:

#### Quick start

* contracts/maths/boolean -> contracts folder not present
* contracts/default.nix -> contracts folder not present
* organisation -> page / section to be created?

#### Fractals

* similar mechanism -> blob not existing anymore so it is not clear which line was pointed by L31

---

### Documentation order

I am not familiar enough with the project to figure what would be a "right" order for the documentation chapters. Any hints?

Current order is defined in -> https://raw.githubusercontent.com/ericsagnes/fractalide/feat/doc-adoc/doc/index.adoc

---

### Title levels

Much more a nitpick, but:

Introduction problems and solution are on a same level:

```
1.4. Problem 0
1.5. Solution
1.6. Problem 1
1.7. Solution
1.8. Problem 2
1.9. Solution
1.10. Problem 3
1.11. Solution
```

The following could be a more natural structure:

```
1.4 Problem: Foo bar baz
   1.4.1 Solution
1.5 Problem: X Y Z
   1.5.1 Solution
```

Edge collections sub contents are the 5 _?_, but nodes fractals ans services have one level in between:

```
3. Nodes collection
   3.1. Subgraphs
4. Edge Collection
   4.1. What?
   4.2. Why?
   4.3. Who?
   4.4. Where?
   4.5. How?
5. Services
   5.1. Reusable services
6. Fractals
   6.1. Third party Fractalide libraries
```
Uniformizing the structure of these similar chapters could make the documentation easier to read.

**Comment by sjmackenzie** [comment]
## Broken links
`contracts/maths/boolean` should be `edges/prim/bool/`
`contracts/default.nix` should be `edges/default.nix`
The `organisation` section iirc was completely removed. That sentence can safely be removed.

## Documentation order
Your documentation order seems perfectly good! 

## Title levels
```
1.4 Problem: Foo bar baz
   1.4.1 Solution
1.5 Problem: X Y Z
   1.5.1 Solution
```
looks great or maybe
```
1.4 State the problem X
   1.4.1 Explain the solution
1.5 State the problem F
   1.5.1 Explain the solution
```
Following the `Reasoning` section [here](https://github.com/ethereumproject/sputnikvm/blob/master/README.md).

I agree with you that it isn't uniform across those similar chapters.

Please restructure the similar chapters as you see fit.

**Comment by ericsagnes** [comment]
Thanks for the quick feedback!

Links are fixed, and I tweaked the titles level to have a more consistent structure, most changes have been done in the top level README.adoc ([preview](https://github.com/ericsagnes/fractalide/blob/feat/doc-adoc/README.adoc)).

If everything looks good for you in the generated doc `nix-build doc`, this should be fine to merge.

**Comment by sjmackenzie** [comment]
it looks really beautiful.

**Comment by sjmackenzie** [comment]
Oh I just noticed,
The `Agent` collection is missing from the top level, see here: https://github.com/fractalide/fractalide/blob/master/nodes/rs/README.md
Later I hope there will be `agent` information about different languages such as `rust` `purescript` etc.

**Comment by sjmackenzie** [comment]
Correction: `Agent` is missing.

So a `node` can come in the form of an `agent` and a `subgraph`. A `subgraph` composes `agents`.
There is only 1 type of `subgraph` hence only one document explaining it: https://github.com/fractalide/fractalide/blob/master/nodes/README.adoc
But `agents` can be implemented in different languages. At the moment there is only a `rust` implementation. (see link in previous comment)

**Comment by sjmackenzie** [comment]
So a logical mapping would be this:

```
3. Nodes collection
3.1. Subgraphs
3.2. Agents 
3.2.1 Rust
3.2.2 Purescript
```

3.2 would be an overview of what an `agent` is.
3.2.1 & 3.2.2 would explain the implementation details of each `agent` subset.

3.2 and 3.2.2 is not written yet.

**Comment by ericsagnes** [comment]
Good catch, I will make another PR to address that.

**Pull request merged**
